# Generated by Django 5.1 on 2024-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisers',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='advisers',
            name='count_sold',
        ),
        migrations.RemoveField(
            model_name='advisers',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='advisers',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='advisers',
            name='work_price',
        ),
        migrations.RemoveField(
            model_name='advisers',
            name='work_time',
        ),
        migrations.AddField(
            model_name='advisers',
            name='profession',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
