# Generated by Django 5.1 on 2024-08-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id', 'name'],
                'indexes': [models.Index(fields=['id', 'name'], name='servic_blog_id_74cef9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='servic/category/')),
                ('views', models.IntegerField(default=0)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id', 'name'],
                'indexes': [models.Index(fields=['id'], name='servic_cate_id_fc20d3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('last_update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id', 'name'],
                'indexes': [models.Index(fields=['id'], name='servic_feat_id_27410a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='servic/blog/')),
                ('name', models.CharField(max_length=60)),
                ('last_update_time', models.DateTimeField(auto_now=True)),
                ('blog_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='servic.blogtype')),
            ],
            options={
                'ordering': ['id', 'name'],
                'indexes': [models.Index(fields=['id', 'name'], name='servic_blog_id_735a4c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servic.category')),
                ('features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servic.features')),
            ],
            options={
                'ordering': ['id', 'short_name'],
                'indexes': [models.Index(fields=['id', 'short_name'], name='servic_serv_id_d812dc_idx')],
            },
        ),
    ]
